// Copyright PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeYuLongs implements YuLongInterface
type FakeYuLongs struct {
	Fake *FakePingcapV1alpha1
	ns   string
}

var yulongsResource = v1alpha1.SchemeGroupVersion.WithResource("yulongs")

var yulongsKind = v1alpha1.SchemeGroupVersion.WithKind("YuLong")

// Get takes name of the yuLong, and returns the corresponding yuLong object, and an error if there is any.
func (c *FakeYuLongs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.YuLong, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(yulongsResource, c.ns, name), &v1alpha1.YuLong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YuLong), err
}

// List takes label and field selectors, and returns the list of YuLongs that match those selectors.
func (c *FakeYuLongs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.YuLongList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(yulongsResource, yulongsKind, c.ns, opts), &v1alpha1.YuLongList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.YuLongList{ListMeta: obj.(*v1alpha1.YuLongList).ListMeta}
	for _, item := range obj.(*v1alpha1.YuLongList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested yuLongs.
func (c *FakeYuLongs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(yulongsResource, c.ns, opts))

}

// Create takes the representation of a yuLong and creates it.  Returns the server's representation of the yuLong, and an error, if there is any.
func (c *FakeYuLongs) Create(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.CreateOptions) (result *v1alpha1.YuLong, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(yulongsResource, c.ns, yuLong), &v1alpha1.YuLong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YuLong), err
}

// Update takes the representation of a yuLong and updates it. Returns the server's representation of the yuLong, and an error, if there is any.
func (c *FakeYuLongs) Update(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.UpdateOptions) (result *v1alpha1.YuLong, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(yulongsResource, c.ns, yuLong), &v1alpha1.YuLong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YuLong), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeYuLongs) UpdateStatus(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.UpdateOptions) (*v1alpha1.YuLong, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(yulongsResource, "status", c.ns, yuLong), &v1alpha1.YuLong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YuLong), err
}

// Delete takes name of the yuLong and deletes it. Returns an error if one occurs.
func (c *FakeYuLongs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(yulongsResource, c.ns, name, opts), &v1alpha1.YuLong{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeYuLongs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(yulongsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.YuLongList{})
	return err
}

// Patch applies the patch and returns the patched yuLong.
func (c *FakeYuLongs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.YuLong, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(yulongsResource, c.ns, name, pt, data, subresources...), &v1alpha1.YuLong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.YuLong), err
}
