// Copyright PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/pingcap/tidb-operator/pkg/apis/pingcap/v1alpha1"
	scheme "github.com/pingcap/tidb-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// YuLongsGetter has a method to return a YuLongInterface.
// A group's client should implement this interface.
type YuLongsGetter interface {
	YuLongs(namespace string) YuLongInterface
}

// YuLongInterface has methods to work with YuLong resources.
type YuLongInterface interface {
	Create(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.CreateOptions) (*v1alpha1.YuLong, error)
	Update(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.UpdateOptions) (*v1alpha1.YuLong, error)
	UpdateStatus(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.UpdateOptions) (*v1alpha1.YuLong, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.YuLong, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.YuLongList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.YuLong, err error)
	YuLongExpansion
}

// yuLongs implements YuLongInterface
type yuLongs struct {
	client rest.Interface
	ns     string
}

// newYuLongs returns a YuLongs
func newYuLongs(c *PingcapV1alpha1Client, namespace string) *yuLongs {
	return &yuLongs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the yuLong, and returns the corresponding yuLong object, and an error if there is any.
func (c *yuLongs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.YuLong, err error) {
	result = &v1alpha1.YuLong{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("yulongs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of YuLongs that match those selectors.
func (c *yuLongs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.YuLongList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.YuLongList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("yulongs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested yuLongs.
func (c *yuLongs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("yulongs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a yuLong and creates it.  Returns the server's representation of the yuLong, and an error, if there is any.
func (c *yuLongs) Create(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.CreateOptions) (result *v1alpha1.YuLong, err error) {
	result = &v1alpha1.YuLong{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("yulongs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(yuLong).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a yuLong and updates it. Returns the server's representation of the yuLong, and an error, if there is any.
func (c *yuLongs) Update(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.UpdateOptions) (result *v1alpha1.YuLong, err error) {
	result = &v1alpha1.YuLong{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("yulongs").
		Name(yuLong.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(yuLong).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *yuLongs) UpdateStatus(ctx context.Context, yuLong *v1alpha1.YuLong, opts v1.UpdateOptions) (result *v1alpha1.YuLong, err error) {
	result = &v1alpha1.YuLong{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("yulongs").
		Name(yuLong.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(yuLong).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the yuLong and deletes it. Returns an error if one occurs.
func (c *yuLongs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("yulongs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *yuLongs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("yulongs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched yuLong.
func (c *yuLongs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.YuLong, err error) {
	result = &v1alpha1.YuLong{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("yulongs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
